language: python

#before_script:
#  - wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
#  - chmod +x miniconda.sh
#  - export PATH=/home/travis/miniconda/bin:$PATH
#  - conda install --yes numpy=1.8
before_script:
  - pip uninstall numpy -y
  - pip install -I numpy==1.8.2

python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
